name: CD demo

run-name: ${{ github.actor }} is testing out CD
on: [push, workflow_dispatch]

jobs:
  cd-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'